version: "3"
services:
  postgres:
    image: 'postgres:13.2'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - "5961:5432"
    environment:
      POSTGRES_PASSWORD: pass123